// <auto-generated />
namespace JH_Service.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class twoMig : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(twoMig));
        
        string IMigrationMetadata.Id
        {
            get { return "202011241425463_twoMig"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
