// <auto-generated />
namespace JH_Service.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class threeMig : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(threeMig));
        
        string IMigrationMetadata.Id
        {
            get { return "202011241450513_threeMig"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
