//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Searth_summary.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReservAccount", Namespace="http://schemas.datacontract.org/2004/07/JH_Service.Models")]
    [System.SerializableAttribute()]
    public partial class ReservAccount : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int access_levelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string loginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int access_level {
            get {
                return this.access_levelField;
            }
            set {
                if ((this.access_levelField.Equals(value) != true)) {
                    this.access_levelField = value;
                    this.RaisePropertyChanged("access_level");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string login {
            get {
                return this.loginField;
            }
            set {
                if ((object.ReferenceEquals(this.loginField, value) != true)) {
                    this.loginField = value;
                    this.RaisePropertyChanged("login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Vacanci", Namespace="http://schemas.datacontract.org/2004/07/JH_Service.Models")]
    [System.SerializableAttribute()]
    public partial class Vacanci : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime create_dataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double experience_jobField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool isValidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string list_summaryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string name_companyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string name_jobField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal salaryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string skillsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string user_idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime create_data {
            get {
                return this.create_dataField;
            }
            set {
                if ((this.create_dataField.Equals(value) != true)) {
                    this.create_dataField = value;
                    this.RaisePropertyChanged("create_data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double experience_job {
            get {
                return this.experience_jobField;
            }
            set {
                if ((this.experience_jobField.Equals(value) != true)) {
                    this.experience_jobField = value;
                    this.RaisePropertyChanged("experience_job");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isValid {
            get {
                return this.isValidField;
            }
            set {
                if ((this.isValidField.Equals(value) != true)) {
                    this.isValidField = value;
                    this.RaisePropertyChanged("isValid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string list_summary {
            get {
                return this.list_summaryField;
            }
            set {
                if ((object.ReferenceEquals(this.list_summaryField, value) != true)) {
                    this.list_summaryField = value;
                    this.RaisePropertyChanged("list_summary");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name_company {
            get {
                return this.name_companyField;
            }
            set {
                if ((object.ReferenceEquals(this.name_companyField, value) != true)) {
                    this.name_companyField = value;
                    this.RaisePropertyChanged("name_company");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name_job {
            get {
                return this.name_jobField;
            }
            set {
                if ((object.ReferenceEquals(this.name_jobField, value) != true)) {
                    this.name_jobField = value;
                    this.RaisePropertyChanged("name_job");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal salary {
            get {
                return this.salaryField;
            }
            set {
                if ((this.salaryField.Equals(value) != true)) {
                    this.salaryField = value;
                    this.RaisePropertyChanged("salary");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string skills {
            get {
                return this.skillsField;
            }
            set {
                if ((object.ReferenceEquals(this.skillsField, value) != true)) {
                    this.skillsField = value;
                    this.RaisePropertyChanged("skills");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string user_id {
            get {
                return this.user_idField;
            }
            set {
                if ((object.ReferenceEquals(this.user_idField, value) != true)) {
                    this.user_idField = value;
                    this.RaisePropertyChanged("user_id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JobSeeker", Namespace="http://schemas.datacontract.org/2004/07/JH_Service.Models")]
    [System.SerializableAttribute()]
    public partial class JobSeeker : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime create_dateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime end_dataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string first_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string last_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double my_experience_jobField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string my_skillsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string name_pref_jobField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal pref_salaryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string user_idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime create_date {
            get {
                return this.create_dateField;
            }
            set {
                if ((this.create_dateField.Equals(value) != true)) {
                    this.create_dateField = value;
                    this.RaisePropertyChanged("create_date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime end_data {
            get {
                return this.end_dataField;
            }
            set {
                if ((this.end_dataField.Equals(value) != true)) {
                    this.end_dataField = value;
                    this.RaisePropertyChanged("end_data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string first_name {
            get {
                return this.first_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.first_nameField, value) != true)) {
                    this.first_nameField = value;
                    this.RaisePropertyChanged("first_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string last_name {
            get {
                return this.last_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.last_nameField, value) != true)) {
                    this.last_nameField = value;
                    this.RaisePropertyChanged("last_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double my_experience_job {
            get {
                return this.my_experience_jobField;
            }
            set {
                if ((this.my_experience_jobField.Equals(value) != true)) {
                    this.my_experience_jobField = value;
                    this.RaisePropertyChanged("my_experience_job");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string my_skills {
            get {
                return this.my_skillsField;
            }
            set {
                if ((object.ReferenceEquals(this.my_skillsField, value) != true)) {
                    this.my_skillsField = value;
                    this.RaisePropertyChanged("my_skills");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name_pref_job {
            get {
                return this.name_pref_jobField;
            }
            set {
                if ((object.ReferenceEquals(this.name_pref_jobField, value) != true)) {
                    this.name_pref_jobField = value;
                    this.RaisePropertyChanged("name_pref_job");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal pref_salary {
            get {
                return this.pref_salaryField;
            }
            set {
                if ((this.pref_salaryField.Equals(value) != true)) {
                    this.pref_salaryField = value;
                    this.RaisePropertyChanged("pref_salary");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string user_id {
            get {
                return this.user_idField;
            }
            set {
                if ((object.ReferenceEquals(this.user_idField, value) != true)) {
                    this.user_idField = value;
                    this.RaisePropertyChanged("user_id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Account", Namespace="http://schemas.datacontract.org/2004/07/JH_Service.Models")]
    [System.SerializableAttribute()]
    public partial class Account : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int access_levelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string companyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime create_dateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string loginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int access_level {
            get {
                return this.access_levelField;
            }
            set {
                if ((this.access_levelField.Equals(value) != true)) {
                    this.access_levelField = value;
                    this.RaisePropertyChanged("access_level");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string company {
            get {
                return this.companyField;
            }
            set {
                if ((object.ReferenceEquals(this.companyField, value) != true)) {
                    this.companyField = value;
                    this.RaisePropertyChanged("company");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime create_date {
            get {
                return this.create_dateField;
            }
            set {
                if ((this.create_dateField.Equals(value) != true)) {
                    this.create_dateField = value;
                    this.RaisePropertyChanged("create_date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string login {
            get {
                return this.loginField;
            }
            set {
                if ((object.ReferenceEquals(this.loginField, value) != true)) {
                    this.loginField = value;
                    this.RaisePropertyChanged("login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/updateAlertUsers", ReplyAction="http://tempuri.org/IService1/updateAlertUsersResponse")]
        void updateAlertUsers(Searth_summary.ServiceReference1.ReservAccount r, int accessLevel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/updateAlertUsers", ReplyAction="http://tempuri.org/IService1/updateAlertUsersResponse")]
        System.Threading.Tasks.Task updateAlertUsersAsync(Searth_summary.ServiceReference1.ReservAccount r, int accessLevel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/updateVacanciItems", ReplyAction="http://tempuri.org/IService1/updateVacanciItemsResponse")]
        void updateVacanciItems(Searth_summary.ServiceReference1.Vacanci v, int accessLevel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/updateVacanciItems", ReplyAction="http://tempuri.org/IService1/updateVacanciItemsResponse")]
        System.Threading.Tasks.Task updateVacanciItemsAsync(Searth_summary.ServiceReference1.Vacanci v, int accessLevel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/updateJobSeeker", ReplyAction="http://tempuri.org/IService1/updateJobSeekerResponse")]
        void updateJobSeeker(Searth_summary.ServiceReference1.JobSeeker j, int accessLevel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/updateJobSeeker", ReplyAction="http://tempuri.org/IService1/updateJobSeekerResponse")]
        System.Threading.Tasks.Task updateJobSeekerAsync(Searth_summary.ServiceReference1.JobSeeker j, int accessLevel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetReservs", ReplyAction="http://tempuri.org/IService1/GetReservsResponse")]
        Searth_summary.ServiceReference1.ReservAccount[] GetReservs();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetReservs", ReplyAction="http://tempuri.org/IService1/GetReservsResponse")]
        System.Threading.Tasks.Task<Searth_summary.ServiceReference1.ReservAccount[]> GetReservsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAccount", ReplyAction="http://tempuri.org/IService1/GetAccountResponse")]
        Searth_summary.ServiceReference1.Account[] GetAccount(int accessLevel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAccount", ReplyAction="http://tempuri.org/IService1/GetAccountResponse")]
        System.Threading.Tasks.Task<Searth_summary.ServiceReference1.Account[]> GetAccountAsync(int accessLevel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetJob", ReplyAction="http://tempuri.org/IService1/GetJobResponse")]
        Searth_summary.ServiceReference1.JobSeeker[] GetJob(int accessLevel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetJob", ReplyAction="http://tempuri.org/IService1/GetJobResponse")]
        System.Threading.Tasks.Task<Searth_summary.ServiceReference1.JobSeeker[]> GetJobAsync(int accessLevel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetVacanci", ReplyAction="http://tempuri.org/IService1/GetVacanciResponse")]
        Searth_summary.ServiceReference1.Vacanci[] GetVacanci(int accessLevel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetVacanci", ReplyAction="http://tempuri.org/IService1/GetVacanciResponse")]
        System.Threading.Tasks.Task<Searth_summary.ServiceReference1.Vacanci[]> GetVacanciAsync(int accessLevel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateVacanci", ReplyAction="http://tempuri.org/IService1/UpdateVacanciResponse")]
        void UpdateVacanci(string id, string v, int accessLevel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateVacanci", ReplyAction="http://tempuri.org/IService1/UpdateVacanciResponse")]
        System.Threading.Tasks.Task UpdateVacanciAsync(string id, string v, int accessLevel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/FindVacanci", ReplyAction="http://tempuri.org/IService1/FindVacanciResponse")]
        Searth_summary.ServiceReference1.Vacanci[] FindVacanci(string nj, int accessLevel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/FindVacanci", ReplyAction="http://tempuri.org/IService1/FindVacanciResponse")]
        System.Threading.Tasks.Task<Searth_summary.ServiceReference1.Vacanci[]> FindVacanciAsync(string nj, int accessLevel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddVacanci", ReplyAction="http://tempuri.org/IService1/AddVacanciResponse")]
        void AddVacanci(Searth_summary.ServiceReference1.Vacanci v, int accessLevel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddVacanci", ReplyAction="http://tempuri.org/IService1/AddVacanciResponse")]
        System.Threading.Tasks.Task AddVacanciAsync(Searth_summary.ServiceReference1.Vacanci v, int accessLevel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddJob", ReplyAction="http://tempuri.org/IService1/AddJobResponse")]
        void AddJob(Searth_summary.ServiceReference1.JobSeeker j, int accessLevel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddJob", ReplyAction="http://tempuri.org/IService1/AddJobResponse")]
        System.Threading.Tasks.Task AddJobAsync(Searth_summary.ServiceReference1.JobSeeker j, int accessLevel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddAccount", ReplyAction="http://tempuri.org/IService1/AddAccountResponse")]
        void AddAccount(string login, string email, int accessLvl, string compami, string hexpassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddAccount", ReplyAction="http://tempuri.org/IService1/AddAccountResponse")]
        System.Threading.Tasks.Task AddAccountAsync(string login, string email, int accessLvl, string compami, string hexpassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Authentication", ReplyAction="http://tempuri.org/IService1/AuthenticationResponse")]
        int Authentication(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Authentication", ReplyAction="http://tempuri.org/IService1/AuthenticationResponse")]
        System.Threading.Tasks.Task<int> AuthenticationAsync(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/updateUser", ReplyAction="http://tempuri.org/IService1/updateUserResponse")]
        void updateUser(Searth_summary.ServiceReference1.Account a, int accessLevel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/updateUser", ReplyAction="http://tempuri.org/IService1/updateUserResponse")]
        System.Threading.Tasks.Task updateUserAsync(Searth_summary.ServiceReference1.Account a, int accessLevel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CrashTable", ReplyAction="http://tempuri.org/IService1/CrashTableResponse")]
        bool CrashTable();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CrashTable", ReplyAction="http://tempuri.org/IService1/CrashTableResponse")]
        System.Threading.Tasks.Task<bool> CrashTableAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Searth_summary.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Searth_summary.ServiceReference1.IService1>, Searth_summary.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void updateAlertUsers(Searth_summary.ServiceReference1.ReservAccount r, int accessLevel) {
            base.Channel.updateAlertUsers(r, accessLevel);
        }
        
        public System.Threading.Tasks.Task updateAlertUsersAsync(Searth_summary.ServiceReference1.ReservAccount r, int accessLevel) {
            return base.Channel.updateAlertUsersAsync(r, accessLevel);
        }
        
        public void updateVacanciItems(Searth_summary.ServiceReference1.Vacanci v, int accessLevel) {
            base.Channel.updateVacanciItems(v, accessLevel);
        }
        
        public System.Threading.Tasks.Task updateVacanciItemsAsync(Searth_summary.ServiceReference1.Vacanci v, int accessLevel) {
            return base.Channel.updateVacanciItemsAsync(v, accessLevel);
        }
        
        public void updateJobSeeker(Searth_summary.ServiceReference1.JobSeeker j, int accessLevel) {
            base.Channel.updateJobSeeker(j, accessLevel);
        }
        
        public System.Threading.Tasks.Task updateJobSeekerAsync(Searth_summary.ServiceReference1.JobSeeker j, int accessLevel) {
            return base.Channel.updateJobSeekerAsync(j, accessLevel);
        }
        
        public Searth_summary.ServiceReference1.ReservAccount[] GetReservs() {
            return base.Channel.GetReservs();
        }
        
        public System.Threading.Tasks.Task<Searth_summary.ServiceReference1.ReservAccount[]> GetReservsAsync() {
            return base.Channel.GetReservsAsync();
        }
        
        public Searth_summary.ServiceReference1.Account[] GetAccount(int accessLevel) {
            return base.Channel.GetAccount(accessLevel);
        }
        
        public System.Threading.Tasks.Task<Searth_summary.ServiceReference1.Account[]> GetAccountAsync(int accessLevel) {
            return base.Channel.GetAccountAsync(accessLevel);
        }
        
        public Searth_summary.ServiceReference1.JobSeeker[] GetJob(int accessLevel) {
            return base.Channel.GetJob(accessLevel);
        }
        
        public System.Threading.Tasks.Task<Searth_summary.ServiceReference1.JobSeeker[]> GetJobAsync(int accessLevel) {
            return base.Channel.GetJobAsync(accessLevel);
        }
        
        public Searth_summary.ServiceReference1.Vacanci[] GetVacanci(int accessLevel) {
            return base.Channel.GetVacanci(accessLevel);
        }
        
        public System.Threading.Tasks.Task<Searth_summary.ServiceReference1.Vacanci[]> GetVacanciAsync(int accessLevel) {
            return base.Channel.GetVacanciAsync(accessLevel);
        }
        
        public void UpdateVacanci(string id, string v, int accessLevel) {
            base.Channel.UpdateVacanci(id, v, accessLevel);
        }
        
        public System.Threading.Tasks.Task UpdateVacanciAsync(string id, string v, int accessLevel) {
            return base.Channel.UpdateVacanciAsync(id, v, accessLevel);
        }
        
        public Searth_summary.ServiceReference1.Vacanci[] FindVacanci(string nj, int accessLevel) {
            return base.Channel.FindVacanci(nj, accessLevel);
        }
        
        public System.Threading.Tasks.Task<Searth_summary.ServiceReference1.Vacanci[]> FindVacanciAsync(string nj, int accessLevel) {
            return base.Channel.FindVacanciAsync(nj, accessLevel);
        }
        
        public void AddVacanci(Searth_summary.ServiceReference1.Vacanci v, int accessLevel) {
            base.Channel.AddVacanci(v, accessLevel);
        }
        
        public System.Threading.Tasks.Task AddVacanciAsync(Searth_summary.ServiceReference1.Vacanci v, int accessLevel) {
            return base.Channel.AddVacanciAsync(v, accessLevel);
        }
        
        public void AddJob(Searth_summary.ServiceReference1.JobSeeker j, int accessLevel) {
            base.Channel.AddJob(j, accessLevel);
        }
        
        public System.Threading.Tasks.Task AddJobAsync(Searth_summary.ServiceReference1.JobSeeker j, int accessLevel) {
            return base.Channel.AddJobAsync(j, accessLevel);
        }
        
        public void AddAccount(string login, string email, int accessLvl, string compami, string hexpassword) {
            base.Channel.AddAccount(login, email, accessLvl, compami, hexpassword);
        }
        
        public System.Threading.Tasks.Task AddAccountAsync(string login, string email, int accessLvl, string compami, string hexpassword) {
            return base.Channel.AddAccountAsync(login, email, accessLvl, compami, hexpassword);
        }
        
        public int Authentication(string login, string password) {
            return base.Channel.Authentication(login, password);
        }
        
        public System.Threading.Tasks.Task<int> AuthenticationAsync(string login, string password) {
            return base.Channel.AuthenticationAsync(login, password);
        }
        
        public void updateUser(Searth_summary.ServiceReference1.Account a, int accessLevel) {
            base.Channel.updateUser(a, accessLevel);
        }
        
        public System.Threading.Tasks.Task updateUserAsync(Searth_summary.ServiceReference1.Account a, int accessLevel) {
            return base.Channel.updateUserAsync(a, accessLevel);
        }
        
        public bool CrashTable() {
            return base.Channel.CrashTable();
        }
        
        public System.Threading.Tasks.Task<bool> CrashTableAsync() {
            return base.Channel.CrashTableAsync();
        }
    }
}
